Repository onosproject/onos-gui, pull requests merged in 2019-08, with the labels that each got.

#15 Added in the onos-topo proto files
  Makefile
  build/bin/compile-protos-ts.sh
  build/compile-protos-ts.sh
  web/onos-gui/angular.json
  web/onos-gui/src/app/onos-config/proto/github.com/onosproject/onos-config/pkg/northbound/proto/adminServiceClientPb.ts
  web/onos-gui/src/app/onos-config/proto/github.com/onosproject/onos-config/pkg/northbound/proto/admin_pb.d.ts
  web/onos-gui/src/app/onos-config/proto/github.com/onosproject/onos-config/pkg/northbound/proto/admin_pb.js
  web/onos-gui/src/app/onos-config/proto/github.com/onosproject/onos-config/pkg/northbound/proto/diagsServiceClientPb.ts
  web/onos-gui/src/app/onos-config/proto/github.com/onosproject/onos-config/pkg/northbound/proto/diags_pb.d.ts
  web/onos-gui/src/app/onos-config/proto/github.com/onosproject/onos-config/pkg/northbound/proto/diags_pb.js
  web/onos-gui/src/app/onos-config/proto/github.com/openconfig/gnmi/proto/gnmi/gnmiServiceClientPb.ts
  web/onos-gui/src/app/onos-config/proto/github.com/openconfig/gnmi/proto/gnmi/gnmi_pb.d.ts
  web/onos-gui/src/app/onos-config/proto/github.com/openconfig/gnmi/proto/gnmi/gnmi_pb.js
  web/onos-gui/src/app/onos-config/proto/github.com/openconfig/gnmi/proto/gnmi_ext/gnmi_ext_pb.d.ts
  web/onos-gui/src/app/onos-config/proto/github.com/openconfig/gnmi/proto/gnmi_ext/gnmi_ext_pb.js
  web/onos-gui/src/app/onos-config/proto/onos-config-admin.service.ts
  web/onos-gui/src/app/onos-topo/proto/github.com/onosproject/onos-topo/pkg/northbound/admin/adminServiceClientPb.ts
  web/onos-gui/src/app/onos-topo/proto/github.com/onosproject/onos-topo/pkg/northbound/admin/admin_pb.d.ts
  web/onos-gui/src/app/onos-topo/proto/github.com/onosproject/onos-topo/pkg/northbound/admin/admin_pb.js
  web/onos-gui/src/app/onos-topo/proto/github.com/onosproject/onos-topo/pkg/northbound/device/deviceServiceClientPb.ts
  web/onos-gui/src/app/onos-topo/proto/github.com/onosproject/onos-topo/pkg/northbound/device/device_pb.d.ts
  web/onos-gui/src/app/onos-topo/proto/github.com/onosproject/onos-topo/pkg/northbound/device/device_pb.js
  web/onos-gui/src/app/onos-topo/proto/github.com/onosproject/onos-topo/pkg/northbound/diags/diagsServiceClientPb.ts
  web/onos-gui/src/app/onos-topo/proto/github.com/onosproject/onos-topo/pkg/northbound/diags/diags_pb.d.ts
  web/onos-gui/src/app/onos-topo/proto/github.com/onosproject/onos-topo/pkg/northbound/diags/diags_pb.js
  web/onos-gui/src/app/onos-topo/proto/onos-topo-device.service.spec.ts
  web/onos-gui/src/app/onos-topo/proto/onos-topo-device.service.ts
Labels: enhancement

#16 Added in link to onos-topo through nginx
  Makefile
  build/bin/compile-protos-ts.sh
  build/docker-compose-latest.yml
  build/docker-compose-stable.yml
  build/envoy-proxy/Dockerfile
  build/envoy-proxy/client1.crt
  build/envoy-proxy/client1.key
  build/envoy-proxy/envoy-config.yaml
  build/envoy-proxy/envoy-topo.yaml
  build/envoy-proxy/onfca.crt
  build/onos-gui/nginx.conf
  web/onos-gui/src/app/onos-config/onos-config.module.ts
  web/onos-gui/src/app/onos-config/proto/onos-config-admin.service.ts
  web/onos-gui/src/app/onos-config/proto/onos-config-diags.service.ts
  web/onos-gui/src/app/onos-config/proto/onos-config-gnmi.service.ts
  web/onos-gui/src/app/onos-topo/onos-topo.module.ts
  web/onos-gui/src/app/onos-topo/proto/gogoproto/gogo_pb.js
  web/onos-gui/src/app/onos-topo/proto/onos-topo-device.service.ts
  web/onos-gui/src/environments/environment.prod.ts
  web/onos-gui/src/environments/environment.ts
Labels: enhancement

#19 Added in display of opState in ConfigView
  build/bin/compile-protos-ts.sh
  build/docker-compose-latest.yml
  build/onos-gui/Dockerfile
  web/onos-gui/src/app/onos-config/change-value.pipe.spec.ts
  web/onos-gui/src/app/onos-config/change-value.pipe.ts
  web/onos-gui/src/app/onos-config/config-utils.ts
  web/onos-gui/src/app/onos-config/config-view/config-view.component.html
  web/onos-gui/src/app/onos-config/config-view/container-svg/container-svg.component.css
  web/onos-gui/src/app/onos-config/config-view/container-svg/container-svg.component.html
  web/onos-gui/src/app/onos-config/config-view/container-svg/container-svg.component.ts
  web/onos-gui/src/app/onos-config/config-view/layer-svg/layer-svg.component.html
  web/onos-gui/src/app/onos-config/config-view/layer-svg/layer-svg.component.ts
  web/onos-gui/src/app/onos-config/onos-config.module.ts
  web/onos-gui/src/app/onos-config/proto/github.com/onosproject/onos-config/pkg/northbound/admin/adminServiceClientPb.ts
  web/onos-gui/src/app/onos-config/proto/github.com/onosproject/onos-config/pkg/northbound/admin/admin_pb.d.ts
  web/onos-gui/src/app/onos-config/proto/github.com/onosproject/onos-config/pkg/northbound/admin/admin_pb.js
  web/onos-gui/src/app/onos-config/proto/github.com/onosproject/onos-config/pkg/northbound/diags/diagsServiceClientPb.ts
  web/onos-gui/src/app/onos-config/proto/github.com/onosproject/onos-config/pkg/northbound/diags/diags_pb.d.ts
  web/onos-gui/src/app/onos-config/proto/github.com/onosproject/onos-config/pkg/northbound/diags/diags_pb.js
  web/onos-gui/src/app/onos-config/proto/github.com/openconfig/gnmi/proto/gnmi/gnmiServiceClientPb.ts
  web/onos-gui/src/app/onos-config/proto/onos-config-diags.service.ts
  web/onos-gui/src/app/onos-config/tree-layout.service.ts
  web/onos-gui/src/app/onos-topo/devices-list/devices-list.component.ts
  web/onos-gui/src/app/onos-topo/proto/github.com/onosproject/onos-topo/pkg/northbound/admin/adminServiceClientPb.ts
  web/onos-gui/src/app/onos-topo/proto/github.com/onosproject/onos-topo/pkg/northbound/device/deviceServiceClientPb.ts
  web/onos-gui/src/app/onos-topo/proto/github.com/onosproject/onos-topo/pkg/northbound/device/device_pb.d.ts
  web/onos-gui/src/app/onos-topo/proto/github.com/onosproject/onos-topo/pkg/northbound/device/device_pb.js
  web/onos-gui/src/app/onos-topo/proto/github.com/onosproject/onos-topo/pkg/northbound/diags/diagsServiceClientPb.ts
  web/onos-gui/src/app/onos-topo/proto/onos-topo-device.service.ts
Labels: enhancement

#22 Made the nodes of the Config view draggable
  Makefile
  docs/run.md
  web/onos-gui/src/app/onos-config/change-value.pipe.spec.ts
  web/onos-gui/src/app/onos-config/change-value.pipe.ts
  web/onos-gui/src/app/onos-config/config-view/container-svg/container-svg.component.css
  web/onos-gui/src/app/onos-config/config-view/draggable/draggable.directive.spec.ts
  web/onos-gui/src/app/onos-config/config-view/draggable/draggable.directive.ts
  web/onos-gui/src/app/onos-config/config-view/layer-svg/layer-svg.component.html
  web/onos-gui/src/app/onos-config/config-view/layer-svg/layer-svg.component.spec.ts
  web/onos-gui/src/app/onos-config/config-view/layer-svg/layer-svg.component.ts
  web/onos-gui/src/app/onos-config/onos-config.module.ts
  web/onos-gui/src/app/onos-config/tree-layout.service.ts
  web/onos-gui/src/app/onos-topo/device-detail/device-detail.component.html
  web/onos-gui/src/environments/environment.ts
  web/onos-gui/src/test.ts
  web/onos-gui/tslint.json
Labels: enhancement

#25 Fix problems with reading numbers out of protobuf messages
  web/onos-gui/src/app/onos-config/change-value.util.spec.ts
  web/onos-gui/src/app/onos-config/change-value.util.ts
Labels: Do Not Merge, bug

#27 Fixed computation of float, int and uint from ByteArray in browser
  web/onos-gui/src/app/onos-config/change-value.util.spec.ts
  web/onos-gui/src/app/onos-config/change-value.util.ts
Labels: bug

#28 Added in a service to handle a hierarchy for a tidy-tree layout
  web/onos-gui/src/app/onos-config/change-value.util.spec.ts
  web/onos-gui/src/app/onos-config/config-view/config-view.component.ts
  web/onos-gui/src/app/onos-config/config-view/hierarchy-layout.service.spec.ts
  web/onos-gui/src/app/onos-config/config-view/hierarchy-layout.service.ts
  web/onos-gui/src/app/onos-config/path.util.spec.ts
  web/onos-gui/src/app/onos-config/path.util.ts
  web/onos-gui/src/app/onos-config/pending-net-change.service.spec.ts
  web/onos-gui/src/app/onos-config/pending-net-change.service.ts
Labels: enhancement

#30 Changed layer view to be a hierarchy tree - part 2 of 2
  web/onos-gui/src/app/onos-config/config-view/config-view.component.html
  web/onos-gui/src/app/onos-config/config-view/config-view.component.ts
  web/onos-gui/src/app/onos-config/config-view/container-svg/container-svg.component.html
  web/onos-gui/src/app/onos-config/config-view/container-svg/container-svg.component.ts
  web/onos-gui/src/app/onos-config/config-view/draggable/draggable.directive.spec.ts
  web/onos-gui/src/app/onos-config/config-view/draggable/draggable.directive.ts
  web/onos-gui/src/app/onos-config/config-view/hierarchy-layout.service.spec.ts
  web/onos-gui/src/app/onos-config/config-view/hierarchy-layout.service.ts
  web/onos-gui/src/app/onos-config/config-view/layer-svg/layer-svg.component.html
  web/onos-gui/src/app/onos-config/config-view/layer-svg/layer-svg.component.spec.ts
  web/onos-gui/src/app/onos-config/config-view/layer-svg/layer-svg.component.ts
  web/onos-gui/src/app/onos-config/config-view/link-filter.pipe.spec.ts
  web/onos-gui/src/app/onos-config/config-view/link-filter.pipe.ts
  web/onos-gui/src/app/onos-config/config-view/string-value/string-value.component.html
  web/onos-gui/src/app/onos-config/config-view/string-value/string-value.component.ts
  web/onos-gui/src/app/onos-config/onos-config.module.ts
  web/onos-gui/src/app/onos-config/path.util.spec.ts
  web/onos-gui/src/app/onos-config/path.util.ts
  web/onos-gui/src/app/onos-config/tree-layout.service.spec.ts
  web/onos-gui/src/app/onos-config/tree-layout.service.ts
Labels: enhancement
